name: main
 
on:  [push, pull_request]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Build and test 
        run: |
          mvn install -DskipTests -am -pl .
          mvn test -pl . -Dtest=com.esotericsoftware.kryonet.PingTest.testPing
       
